[profile.default]
src = "src/contracts"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Solidity compiler settings
solc_version = "0.8.23"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = false

# Test settings
verbosity = 2
gas_reports = ["*"]
gas_limit = 30000000

# RPC settings for testing
eth_rpc_url = "https://eth-mainnet.alchemyapi.io/v2/YOUR_API_KEY"

# Fuzz testing
fuzz = { runs = 256 }

# Inspector integration settings
[profile.inspector]
inherits = "default"
verbosity = 3
gas_reports = ["*"]
# Enable detailed tracing for inspector
extra_output = ["storageLayout", "metadata"]